FROM cgr.dev/chainguard/wolfi-base AS build

RUN apk update && apk add --no-cache traefik
RUN which traefik

FROM cgr.dev/chainguard/static

COPY --from=build /usr/bin/traefik /usr/bin/traefik

EXPOSE 8080/tcp 80/tcp

# Using a Containerfile to configure /var/logs in a container is a poor practice 
# and should be avoided in most scenarios. 
# The best practice is to have applications inside the container write logs to stdout and stderr instead of files. 
# A container orchestrator like Docker or Kubernetes then captures these streams and handles the logging for you

# For modern containerized applications, logging to stdout and stderr is the standard. 
# This approach works with Docker's default logging mechanism, 
# which collects these streams and stores them in JSON files on the host system

# Use a symbolic link to redirect the log files to stdout/stderr
# This is a common pattern for applications not originally designed for containers.
#RUN ln -sf /dev/stdout /var/log/nginx/access.log && \
#    ln -sf /dev/stderr /var/log/nginx/error.log

ENTRYPOINT ["/usr/bin/traefik"]
